# Generated by Django 4.1.7 on 2023-02-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produits',
            new_name='Produit',
        ),
    ]
