# Generated by Django 4.1.7 on 2023-02-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0002_rename_produits_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='Img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
